In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.decomposition import PCA

In [2]:
x,y = make_classification(n_features=5, n_classes=2, n_samples=20)

In [3]:
x

array([[-1.26702643, -0.24767198,  0.40781419,  1.13258121,  0.92218845],
       [ 0.04770906,  0.30547147, -1.34443642, -1.45629943, -0.00930001],
       [ 0.50295236, -0.27390301,  0.57411577,  1.26122489,  0.85480907],
       [-1.73648602,  0.27140304, -0.07563314, -1.21489046, -1.5082788 ],
       [-0.08986984, -0.3568809 ,  2.95931881,  1.79942451, -1.85080547],
       [-0.76789506,  0.57973088, -2.13552419, -2.7344309 , -0.57533667],
       [ 1.95377693, -0.3471419 ,  3.25772237,  1.77708839, -2.30862545],
       [-0.35579499, -0.22082497,  1.61580817,  1.09821771, -0.85655189],
       [ 0.07279566,  0.12623376, -2.38148109, -0.73071351,  2.44407634],
       [ 1.2647907 ,  0.50298297, -1.67357677, -2.35977809, -0.73946431],
       [-2.14833609,  0.32718943, -1.6270721 , -1.57304307,  0.24081092],
       [ 0.16632103, -0.37032885,  2.77478424,  1.84632926, -1.52364784],
       [-0.9109574 , -0.14253531, -0.27698515,  0.61567608,  1.21671308],
       [-2.65261357,  0.77494858, -2.1

In [4]:
x1_mean = x[:,0].mean()
x2_mean = x[:,1].mean()
x3_mean = x[:,2].mean()
x4_mean = x[:,3].mean()
x5_mean = x[:,4].mean()

In [5]:
x1 = x[:,0]-x1_mean
x2 = x[:,1]-x2_mean
x3 = x[:,2]-x3_mean
x4 = x[:,3]-x4_mean
x5 = x[:,4]-x5_mean

In [6]:
data = np.array([x1, x2, x3, x4, x5]).T
data

array([[-0.77198119, -0.30621356,  0.57896796,  1.40556455,  1.03993611],
       [ 0.54275429,  0.24692989, -1.17328265, -1.18331609,  0.10844765],
       [ 0.99799759, -0.3324446 ,  0.74526954,  1.53420823,  0.97255674],
       [-1.24144079,  0.21286146,  0.09552063, -0.94190713, -1.39053113],
       [ 0.40517539, -0.41542249,  3.13047258,  2.07240784, -1.7330578 ],
       [-0.27284983,  0.5211893 , -1.96437042, -2.46144756, -0.45758901],
       [ 2.44882216, -0.40568348,  3.42887614,  2.05007172, -2.19087779],
       [ 0.13925025, -0.27936656,  1.78696194,  1.37120105, -0.73880422],
       [ 0.5678409 ,  0.06769218, -2.21032732, -0.45773017,  2.56182401],
       [ 1.75983593,  0.44444138, -1.502423  , -2.08679476, -0.62171665],
       [-1.65329086,  0.26864785, -1.45591833, -1.30005973,  0.35855858],
       [ 0.66136627, -0.42887043,  2.94593801,  2.1193126 , -1.40590018],
       [-0.41591217, -0.20107689, -0.10583138,  0.88865941,  1.33446074],
       [-2.15756834,  0.716407  , -1.9

In [7]:
cov_matrix = np.cov(data.T)
cov_matrix

array([[ 1.18263073, -0.16717539,  0.893047  ,  0.80809284, -0.20576603],
       [-0.16717539,  0.13291409, -0.59709426, -0.63450766,  0.01219526],
       [ 0.893047  , -0.59709426,  3.97651313,  2.94178745, -1.78982676],
       [ 0.80809284, -0.63450766,  2.94178745,  3.03547453, -0.18071198],
       [-0.20576603,  0.01219526, -1.78982676, -0.18071198,  2.32722404]])

In [8]:
eig_value, eig_vec = np.linalg.eig(cov_matrix)

In [9]:
eig_value

array([ 7.31249629e+00,  9.15560448e-01,  2.42669978e+00, -4.05147534e-16,
       -8.57087441e-17])

In [10]:
eig_vec

array([[ 1.95011667e-01, -9.72739571e-01, -1.25491741e-01,
        -4.88619024e-17, -5.74034630e-17],
       [-1.16435793e-01, -3.82577850e-02,  1.15613371e-01,
         1.89722988e-01, -7.19805604e-01],
       [ 7.33053976e-01,  1.32387583e-01,  1.12959125e-01,
         6.55728468e-01, -5.03313821e-01],
       [ 5.70668259e-01,  1.79848467e-01, -5.07274431e-01,
        -5.68496116e-01,  3.15958405e-01],
       [-2.92203291e-01,  4.94178738e-02, -8.37136941e-01,
         4.59170481e-01, -3.58783188e-01]])

In [11]:
pc = np.dot(data, eig_vec)
pc

array([[ 8.07761958e-01,  1.14347994e+00, -1.45670130e+00,
         2.30767024e-16, -4.53615884e-17],
       [-1.48995726e+00, -9.00191952e-01,  3.37384697e-01,
        -1.80981791e-16, -9.33254554e-17],
       [ 1.37099208e+00, -5.35422036e-01, -1.67191828e+00,
         1.40290719e-16, -1.35516265e-16],
       [-3.28057082e-01,  9.73983075e-01,  1.83306050e+00,
        -3.26972277e-16,  3.88675806e-16],
       [ 4.11125191e+00,  3.23274049e-01,  6.54268079e-01,
         8.91388466e-17,  2.73056779e-16],
       [-2.82484451e+00, -4.79886617e-01,  1.50429736e+00,
        -6.75252777e-16,  2.68490768e-16],
       [ 4.84842882e+00, -1.65217131e+00,  8.27229219e-01,
        -3.67712847e-16,  4.48842809e-16],
       [ 2.36800518e+00,  3.21903565e-01,  7.49854669e-02,
        -5.98471164e-17,  1.28735699e-16],
       [-2.52722091e+00, -8.03293129e-01, -2.22551256e+00,
         7.59715484e-17, -5.45040952e-16],
       [-1.81911737e+00, -2.33379829e+00,  1.23986570e+00,
        -4.57717316e-16

In [12]:
principal_comp = pc[:,:2]
principal_comp

array([[ 0.80776196,  1.14347994],
       [-1.48995726, -0.90019195],
       [ 1.37099208, -0.53542204],
       [-0.32805708,  0.97398307],
       [ 4.11125191,  0.32327405],
       [-2.82484451, -0.47988662],
       [ 4.84842882, -1.65217131],
       [ 2.36800518,  0.32190356],
       [-2.52722091, -0.80329313],
       [-1.81911737, -2.33379829],
       [-2.26763277,  1.18910351],
       [ 3.95867467,  0.07475463],
       [-0.01807939,  0.62402646],
       [-3.35313063,  1.13366015],
       [-3.31578728,  0.55022623],
       [-2.82607906, -0.8721183 ],
       [-0.30670205,  0.14316758],
       [-1.87600969,  0.03546693],
       [ 3.32546692,  0.3952861 ],
       [ 2.16203645,  0.6685494 ]])

In [13]:
pc1 = PCA(n_components=2)

In [14]:
pc1.fit_transform(x)

array([[ 0.80776196, -1.4567013 ],
       [-1.48995726,  0.3373847 ],
       [ 1.37099208, -1.67191828],
       [-0.32805708,  1.8330605 ],
       [ 4.11125191,  0.65426808],
       [-2.82484451,  1.50429736],
       [ 4.84842882,  0.82722922],
       [ 2.36800518,  0.07498547],
       [-2.52722091, -2.22551256],
       [-1.81911737,  1.2398657 ],
       [-2.26763277,  0.4333988 ],
       [ 3.95867467,  0.3020493 ],
       [-0.01807939, -1.55092884],
       [-3.35313063,  3.19473344],
       [-3.31578728, -2.82770617],
       [-2.82607906, -1.52552642],
       [-0.30670205,  1.11393552],
       [-1.87600969,  1.00265962],
       [ 3.32546692,  0.26229487],
       [ 2.16203645, -1.52186901]])